### ISSUE TITLE
avoid pushing images to latest tag?

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#10]
The current latest tagged image is not working with the current system, breaking updage.
We should avoid pushing images to latest tag if changes break compatibility.

**Comment by craigmulligan** [comment]
I think It's better to use tags instead of pulling latest. Rather freeze it to a specific build like `v0.1.1`. 
I've updated `latest` too.

**Comment by cskiraly** [comment]
With component specific version tags, we would be binding agile-stack repo version to docker image version. Without (i.e. with "latest" or with some other mutable tag), we keep this binding more loose.
With the former (component specific version tags), update procedure is to update agile-stack, than updata images. With the latter, you just simply update images.

It is not yet clear to me which one is better.
