### ISSUE TITLE
Show WS endpoint in Device Manager

### ISSUE THREAD

**Issue by rosogon** [Agile-IoT/agile-ui#11]
I suggest to show the WS endpoint for each (device, component) in the devices tab. This way it will be much easier to subscribe to a stream in nodered.

**Comment by craigmulligan** [comment]
@rosogon do you mean just printing out the ws://<url> in plain text?

**Comment by rosogon** [comment]
@craig-mulligan : yes, just that. It can be pretty printed with a link, f.e., but the point is having a place where to copy the endpoint so it can be easily pasted in nodered. Except the IP (or address), I expect the rest is very easy to build.

**Comment by rosogon** [comment]
@craig-mulligan : I was using the websocket node instead of AgileDeviceRead node. Using the latter, the websocket endpoint is not needed, and it is the agile-way of doing this. So, I close this issue.
