### ISSUE TITLE
fails to build on Travis (travis branch)

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#12]
See https://travis-ci.org/Agile-IoT/agile-ui/jobs/213748957

Build stops with `Unknown system error -96: Unknown system error -96, uv_interface_addresses`

**Comment by craigmulligan** [comment]
Urrgh this sent me in some circles to find the actual issue. But basically there is a tiny change we just made to our qemu binary, so all it actually took was updating the base image to a build after the qemu patch.

**Comment by cskiraly** [comment]
Actually, in the travis file I'm also having this line
`- docker run --rm --privileged multiarch/qemu-user-static:register`
which might interfere with the build. I'm just putting it here for reference, in case we still see issues.
