### ISSUE TITLE
wget not working in alpine image

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#21]
```
bash-4.3# wget -O- https://getcaddy.com
Connecting to getcaddy.com (138.68.240.78:443)
wget: error getting response: Connection reset by peer
```

While it works from other images, from browser, etc.

**Comment by craigmulligan** [comment]
I stripped out the silent flags from the script and ran from a vanilla alpine image:

```
Downloading Caddy for linux/amd64...
https://caddyserver.com/download/linux/amd64?plugins=
--2017-05-30 11:51:37--  https://caddyserver.com/download/linux/amd64?plugins=
Resolving caddyserver.com... 138.68.240.78, 2604:a880:2:d0::1145:e001
Connecting to caddyserver.com|138.68.240.78|:443... connected.
ERROR: cannot verify caddyserver.com's certificate, issued by 'CN=Let\'s Encrypt Authority X3,O=Let\'s Encrypt,C=US':
  Unable to locally verify the issuer's authority.
To connect to caddyserver.com insecurely, use `--no-check-certificate'.
Aborted, error 5 in command: wget "$caddy_url" -O "$PREFIX/tmp/$caddy_file"
``` 

Seems alpine doesn't ship with ssl support, simplest fix would be to install and run it that way curl.

**Comment by cskiraly** [comment]
As a note, I had the same problem with wget on OS X, but there at least you get an error message about "HTTPS support not compiled in."
Would you mind trying an improved dockerfile with multi-stage and curl or a better wget installed? If not, just merge this as is ;-)

**Comment by craigmulligan** [comment]
I'll add multi-stage later, merged the PR for now.
