### ISSUE TITLE
Device discovery switch not moving to on position

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#26]
When device discovery is turned on, the Device discovery switch on the Settings sidepanel is not moving to on position. Device discovery does start. 
Next time its triggered, it is trying to start device discovery again.

**Comment by craigmulligan** [comment]
This is because of https://github.com/Agile-IoT/agile-core/issues/39 basically it returns a 500, so the ui never gets the correct state to update the toggle.

**Comment by cskiraly** [comment]
@craig-mulligan, can you check again? I think with the current version toggled is not updated after onToggle.

**Comment by cskiraly** [comment]
@craig-mulligan this needs urgent fixing
