### ISSUE TITLE
Model for IDM attributes

### ISSUE THREAD

**Issue by nopbyte** [Agile-IoT/agile-ui#28]
Hi @craig-mulligan,

As agreed, here is some info on how attributes relate to devices so we can discuss how to do the state mapping when extending the UI. I have created this issue to keep track of our discussion publicly, so that everyone extending the UI can also have a look.

IDM handles entities and their attributes (also the credentials object used for cloud credentials is an attribute). So, in general an entity, such as a device, can have types of attributes described with json-schema in the configuration files for agile-idm.

In general, we need to store in IDM the same devices that are managed by the device manager once their are "paired". Also, we will need to have attributes that represent anything related to security (for example, if we want to have policies per stream, e.g. temperature or humidity, in a device that has more than one stream. this should be an attribute).

So relationships look like this:
device <-> entity (one-to-one)
and then entity <-> attribute (one-to-many)

There is a particular case of attribute which is the credential object so a credential attribute has several values, i.e. dropbox, xively, etc.

I have created a branch (security) containing some initial changes that use the sdk. To open the window you need to call the window passing the token as a query argument. like: http://localhost:3000/?token=XyvwdW3sc. And then this token is used to query the attributes.

**Comment by craigmulligan** [comment]
Closed with https://github.com/Agile-IoT/agile-ui/pull/42
