### ISSUE TITLE
Connect uses wrong API call

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#3]
Connect button on Device UI is not working.
It should POST to device/{id}/connection, but I think it calls something else.

**Comment by cskiraly** [comment]
See
https://github.com/Agile-IoT/agile-ui/blob/87340c4d0df5b584a78c106e23fbdaff67d9046e/src/js/services/agileCore.js#L58

it is now "connect", it should be "connection"

**Comment by craigmulligan** [comment]
thanks will update. 

be good to update the api to not return 200 on `device/{id}/connect` then too.
