### ISSUE TITLE
images with master and latest tag not up to date 

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#32]
I still think we should have docker image tags pointing to branch heads, and a "latest" docker tag pointing to master.

**Comment by craigmulligan** [comment]
@cskiraly this should be sorted with the lastest ci scripts right?

**Comment by cskiraly** [comment]
Ideally yes. Lets close this when ci scripts is correctly tested

**Comment by craigmulligan** [comment]
Fixed, thanks @cskiraly
