### ISSUE TITLE
Oxymeter (Medical) registered as SensorTag

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#4]
The oxymeter is registered as a SensorTag.

/typeof and then /register sequence works well when used from the script in tests/http/registerDevice2.sh, so it should be some issue with the use of /typeof

**Comment by craigmulligan** [comment]
@cskiraly could you update the docs to include `/typeof`. Currently when posting to `typeof` I get a `method not allowed err`.

**Comment by cskiraly** [comment]
Use this as reference: https://github.com/Agile-IoT/agile-core/blob/master/test/http/registerDevice2.sh
It is scoped: /api/devices/typeof
it takes a DeviceOverview
it produces an array of strings

I have also updated swagger, but the output looks ugly.

**Comment by craigmulligan** [comment]
Have you tested it lately? I'm still getting `405`s 

Here is what I'm doing

```
curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{
    "id": "B0:B4:48:BD:10:85",
    "protocol": "iot.agile.protocol.BLE",
    "name": "CC2650 SensorTag",
    "status": "CONNECTED"
}' "http://217.77.95.110:8080/api/devices/typeof"
```

response: 

```
{
  "code": "INTERNAL_SERVER_ERROR",
  "message": "HTTP 405 Method Not Allowed"
}
```

**Comment by cskiraly** [comment]
found it. You can either use GET, with the same code, or wait till I restart it, and then it will be POST (GET will also work, simplify life).

**Comment by cskiraly** [comment]
I think there is also a glitch in the documentation of /api/devices/register
What you need is 1 object with two fields. The first is a DeviceObject, the second is string. I try to update swagger to reflect this.

**Comment by cskiraly** [comment]
I have also updated /api/devices/register

**Comment by cskiraly** [comment]
fixed in https://github.com/Agile-IoT/agile-ui/commit/08329b6a399a2e6cc1b09e6a558e30ea146f1177
