### ISSUE TITLE
view data tab not showing real-time data

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#48]
@Exulansis I though you also wanted to subscribe on the "view data" tab. Now it only subscribes on the "configure" tab.

**Comment by cskiraly** [comment]
@Exulansis 
I see you have pushed a patch on this to master. Please don't forget the Change-type in the commit message. 
My initial tests show it working, thanks!

**Comment by Exulansis** [comment]
This is solved and will soon be merged in the "Policies" tab.

**Comment by cskiraly** [comment]
@Exulansis, which patch/branch needs merge for this to be fixed?

**Comment by Exulansis** [comment]
@cskiraly Should be in the master branch now (2.1.1).
