### ISSUE TITLE
WS support

### ISSUE THREAD

**Issue by craigmulligan** [Agile-IoT/agile-ui#5]
Hey @cskiraly when you are back in Italy, could you change the test server so one can discover and register devices again? I'd like to test + merge my latest websocket work. 

Once that's all working we should get together and discuss what's next on the roadmap.  

cc @curcuz @hdoukas

**Comment by cskiraly** [comment]
test server is not needed anymore, and WS was added https://github.com/Agile-IoT/agile-ui/commit/12a9e373e8c88f8a262c77ea9fdf1938b20f6998. Closing this issue.
