### ISSUE TITLE
Display units on Devices tab in the data qiuck peek

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#54]
Units are provided, so why not show them?

**Comment by Exulansis** [comment]
@cskiraly Could you please elaborate?
The devices tab currently display the devices that we have paired with.

**Comment by cskiraly** [comment]
With units I mean the measurement unit from the RecordObject, like e.g. "celsius" for temperature.

**Comment by Exulansis** [comment]
Fixed by PR #72
