### ISSUE TITLE
User entity can't be deleted - Fails with status code 400

### ISSUE THREAD

**Issue by agribu** [Agile-IoT/agile-ui#55]
User entity can't be deleted.
Request failed with status code 400

**Comment by Exulansis** [comment]
Thank you for the report, will look into it today, and perhaps ping @nopbyte if appropriate.

**Comment by Exulansis** [comment]
Was not able to reproduce this with recent testing. 
I can confirm this happens sometimes, but at the moment it's not fully clear what causes it. Restarting the agile stack or removing the IDM folder (basically starting anew) seems to solve it.

I will try to profile the issue further and collect meaningful logs if I encounter it again.
