### ISSUE TITLE
Dockerfile not building

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-ui#6]
I would expect the Dockerfile to build from a clean working tree. Instead, it seems it needs some
compilation steps in the host. @craig-mulligan, can you check how you've build the actual image?

**Comment by craigmulligan** [comment]
Yea it needs an `npm run build` will add. Thanks!

**Comment by cskiraly** [comment]
@craig-mulligan I was giving it a quick try, but it wasn't enough. Can you give this some priority (this is only one we can't generate at the moment)?

**Comment by craigmulligan** [comment]
uggh. I SASS binary doesn't run on `arm`? 😢  I'm fixing a bunch of ui stuff atm, so will only get to this later. Do you need a build urgently?

**Comment by cskiraly** [comment]
Would be nice to have this as well for consistency (i.e. to have all actually used modules building), but otherwise no urgency.

**Comment by craigmulligan** [comment]
Cool, sweet yea I'm hoping to have versioned and improved UI PR'd to `agile-stack` today.

**Comment by craigmulligan** [comment]
@cskiraly I just did a fresh clone and build with no problems, what error are you seeing?

**Comment by cskiraly** [comment]
Sorry, it seems my local copy was victim of repo renaming issues :(
Fresh clone works on my side as well.
