### ISSUE TITLE
couldn't get sensor data from my tag in the device manager

### ISSUE THREAD

**Issue by brettdaman** [Agile-IoT/agile-ui#7]
Today I updated our pi with the latest agile code and did some testing and I couldn't get sensor data from my tag in the device manager
Next I used the api  (outside the GUI)  to subscribe to the temperate and I received the data
I went back to the GUI devicemanager and now I can see the temperature data with a wrong last updated
The button view data also doesnt work,  a notification appears "Opening visualizations for CC2650 SensorTag" but nothing opens

![sensortag_data_720](https://cloud.githubusercontent.com/assets/14179855/22927930/0d8717d8-f2b4-11e6-9067-2b3d3aef29dc.jpg)

**Comment by craigmulligan** [comment]
Hey @brettdaman 👋  thanks for reporting, it was working before or is this a completely new setup? It's probably that there is some api incompatibility that has come up. 

Opening visualisations for CC2650 SensorTag requires the Grafana services to be set up, which I'm not sure are.

It'd be helpful too if you can paste errors from your console here.

**Comment by brettdaman** [comment]
It was a new raspberry pi image with the agile-script instructions

**Comment by craigmulligan** [comment]
Cool I'll try take a look at it this week. 

FYI we are merging `agile-scripts` with [agile-resin](https://github.com/Agile-IoT/agile-resin) so maybe better to start setting up PIs with that method from now.

**Comment by cskiraly** [comment]
@craig-mulligan I was not yet orienting people to agile-resin, because we need to sort out this issues first: https://github.com/Agile-IoT/agile-resin/issues/9
Ideally also this one: https://github.com/Agile-IoT/agile-resin/issues/12

**Comment by craigmulligan** [comment]
@brettdaman have you pulled the UI lately, is it resolved?

**Comment by brettdaman** [comment]
I have not used the GUI since. Will pick it up after Graz.

**Comment by brettdaman** [comment]
Tried it again and it works
