### ISSUE TITLE
Wrong units of measurement

### ISSUE THREAD

**Issue by david-gomez-fernandez** [Agile-IoT/agile-ui#86]
Even though devices are successfully registered (output from the REST API below), when it comes to "View data", the unit of measurement is always the same (some examples pasted under the code snippet):

`{
    "deviceId": "lora3339343771356214",
    "address": "3339343771356214",
    "name": "Seeduino",
    "description": "",
    "protocol": "org.eclipse.agail.protocol.LoRa",
    "path": "/org/eclipse/agail/Device/lora3339343771356214",
    "streams": [
        {
            "id": "Temperature",
            "unit": "Degree celsius (°C)"
        },
        {
            "id": "Relative_Humidity",
            "unit": "Relative humidity (%RH)"
        },
        {
            "id": "Latitude",
            "unit": "Decimal degrees (º)"
        },
        {
            "id": "Longitude",
            "unit": "Decimal degrees (º)"
        },
        {
            "id": "Altitude",
            "unit": "Meters (m)"
        },
        {
            "id": "SNR",
            "unit": "Decibel (db)"
        },
        {
            "id": "RSSI",
            "unit": "Decibel-milliwatt (dBm)"
        }
    ]
}`

And here the figures:

![image](https://user-images.githubusercontent.com/1568677/42159762-2f845d14-7df5-11e8-8ad0-3303ceafbea5.png)

![image](https://user-images.githubusercontent.com/1568677/42159796-4c055e20-7df5-11e8-9e76-05dfac4f252d.png)

**Comment by Exulansis** [comment]
Thank you for reporting. This is fixed in the "fix remote discovery" branch. The branch will be merged throughout the next days.
